apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:Lg6O1tPkHF93d/Va5UiEm+97oeKl02VDzA==,iv:yMj78bH3qYzP+5yrnKOf2YGjKOenQLlInUChDSe67Q0=,tag:hiXlklK5FY+JNizVoIY63Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-10-01T09:10:21Z"
    mac: ENC[AES256_GCM,data:KgEFtmUyjh/FikfArImjeFz7fUt1kPErz2oOTOBqC3XeReL26+f1/GACTtOadsdhC9Z1cY8wMmTVG3wsPknAZI3KxJ/OjdWLuLMZGC5dfDIXeI2YT3GCdn2/KTosirFQY+700pswxmSmX85lZYlO61WPvYYZfXbOj/dqgoZl+WE=,iv:1kU+rQZnGyL/WWDeo2vu/pN1N0nISGjh9tVBtXmvCks=,tag:EYdMhF4uoWbhRNmdnYRohA==,type:str]
    pgp:
        - created_at: "2025-10-01T09:10:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2MGViL3zrwyAQv9HbPUdpel+CHr329N6CKw1gPglKicXMKTNvu7UR0CoGYU
            VDkRTcGBeNxV6kfh7aZuHSZtYmbH5r2Wf+fOoY0IclcYa+Oev184pVKVbaFvMC+V
            fkVajKnnfQ4KzeFGz/1C0JpsN8NCN+Tk8Yv2QQcLrTuktJP7K2IMyzNPRtCmhY11
            /6pmvTnqDmuG5dFn3g8+cuT/ZBpK9eF911lVVIkyghR2ZyhnXLN2GQ377vzMMADA
            56dlqGBXU7Y5N3x2zSbECJ9jAAnh+q0lWxQ1BtFpfpIbshsKttH0dJ44F4SGF54+
            wj21gf5IQX3q9ksnrbMNwdUPs5oV46R5hO6B6y1mLATHYD4Omf43lh/5J/i0CIPy
            werWJMIIHMD2JU9tpZUkvH1AwRHDO7TCkMcUpyXcnYfGnLTuu47VsozDvfzU/+HA
            tDXQxB3w86f+XH6zFj/I4dNiju9G36ZcU5ZWhwA1sn3tRf19mB3HM4Y1Al43typA
            ifvFdGpWW+mK0oYTRiak1GgBCQIQ9AQ02pwAlaNTs4VJnmuZucWPL9maQysCzS+p
            2t2hBCDIPnwiWEzgUxIo3FnH19IZO9pVj3MN/qFub64OeRm8aEsNoHP+ueHFuFR2
            3JGWCcvm7hmavjeRg31eJ8yn+1BfHsPzDA==
            =Yoao
            -----END PGP MESSAGE-----
          fp: DE7EDFAC5EF9267BC32DB8C4940D85897F98AE31
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
